---
subparagraph: yes
execute:
  echo: false
geometry:
  - top=20mm
  - left=20mm
  - right=20mm
  - bottom=20mm
format:
    quarto-cv-pdf: 
        keep-tex: true
        keep-md: true
        pdf-engine: lualatex
author: Frederick Joseph Boehm, III
date: last-modified
phone: 715-252-3929
address: "South Dakota State University · 136 E Bluebell Dr · Brookings, South Dakota 57006 · USA"
email: frederick.boehm@gmail.com
fontsize: 10pt
github: fboehm # github account
orcid: 0000-0002-1644-5931 # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
web: fboehm.us
fontawesome: yes
validate-yaml: false
engine: jupyter
---

<!-- quarto cv template: https://github.com/mps9506/quarto-cv -->



```{python}
#| tags: [parameters]

#text_size_text = "\\footnotesize "
#text_size_text = "\\small "
text_size_text = "\\normalsize "
```

```{python}
```

```{python}
```


```{python} 
import yaml
from IPython.display import display, Markdown, display_latex
from datetime import datetime
```


<!---

# Updated  <!-- need to have this line due to issue with quarto-cv-pdf templating -->



# Education and Training  

\hrule

**University of Michigan** \hfill Ann Arbor, Michigan, USA  
Postdoctoral Research Fellow, Department of Internal Medicine ([NIH T32 HL007853](https://reporter.nih.gov/search/edYVbhxf0Uu_nQ9-JqHDJA/project-details/10576923)) \hfill 2023 to 2024  
Postdoctoral Research Fellow, Department of Biostatistics \hfill 2021 to 2023  

**University of Massachusetts Medical School** \hfill Worcester, Massachusetts, USA  
Postdoctoral Research Fellow, Department of Microbiology & Physiological Systems \hfill 2019 to 2021  

**University of Wisconsin-Madison** \hfill Madison, Wisconsin, USA  
Postdoctoral Research Fellow, Department of Biostatistics and Medical Informatics \hfill 2019     
Ph.D., Department of Statistics \hfill 2011 to 2019  
Postdoctoral Research Fellow ([NIH T32 ES007015](https://reporter.nih.gov/search/QFqt1UAzrUORCW6sbBz0qw/project-details/8296307)), Molecular and Environmental Toxicology Center \hfill 2012 to 2014  
Assistant Researcher, [Value-Added Research Center](https://varc.wceruw.org/) \hfill 2011  


**University of Washington** \hfill Seattle, Washington, USA   
Postdoctoral Research Fellow, Department of Biostatistics \hfill 2007 to 2009   

**University of Wisconsin-Madison** \hfill Madison, Wisconsin, USA  
M.D., School of Medicine and Public Health \hfill 2003 to 2007  
M.S., Department of Population Health Sciences \hfill 2003 to 2007  
Graduate Project Assistant, Department of Population Health Sciences \hfill 2003   

[**La Clinica de los Campesinos**](https://famhealth.org/) \hfill Wautoma, Wisconsin, USA  
Spanish Language Medical Interpreter \hfill 2002   

**University of Wisconsin-Madison** \hfill Madison, Wisconsin, USA  
B.S., with Honors in Chemistry, Mathematics, and Biochemistry \hfill 1996 to 2001    






# Written Works 

\hrule

{{< include try-bib.qmd >}}



## Unpublished Manuscripts


```{python}
display(Markdown('\n'.join(fmo_manuscript)))
```





## Journal Articles 


```{python}
display(Markdown('\n'.join(fmo_article)))
```




## Edited Book  




```{python}
display(Markdown('\n'.join(fmo_book)))
```


## Book Chapters


```{python}
display(Markdown('\n'.join(fmo_chapter)))
```



## Software



```{python}
display(Markdown('\n'.join(fmo_software)))
```



## Conference Proceedings




```{python}
display(Markdown('\n'.join(fmo_conference)))
```


## Ph.D. Thesis



```{python}
display(Markdown('\n'.join(fmo_thesis)))
```


## Other Publications




```{python}
display(Markdown('\n'.join(fmo_other)))
```



# Teaching Experience

\hrule

{{< include teaching.qmd >}}


## Formal Courses


```{python}
display(Markdown(markdown_output_formal))
```





## Short Courses & Workshops


```{python}
display(Markdown(markdown_output_short))
```




## Training in Teaching  

```{python}

# Read YAML file
with open("data/teacher-training.yaml", "r") as file:
    data = yaml.safe_load(file)
```

```{python}
markdown_output = ""

for tcourse in data['courses']:
    #foo = f"\\footnotesize {tcourse['title']}, {tcourse['institution']} \hfill {tcourse['term']}  \n"
    foo = text_size_text + f"{tcourse['title']}, {tcourse['institution']} \\hfill {tcourse['term']}  \n"
    markdown_output += foo
display(Markdown(markdown_output))
```


# Mentoring Experience

\hrule


```{python} 

# Read YAML file
with open("data/mentoring.yaml", "r") as file:
    data = yaml.safe_load(file)

# Select elements
```





```{python}
markdown_output = ""

for person in data['people']:
    #foo = f"\\footnotesize Research mentor to {person['name']}, {person['title']} \hfill {person['start']} to {person['end']}   \nProject: {person['project']}   \nNext position: {person['next_role']}  \n"
    foo = text_size_text + f"Research mentor to {person['name']}, {person['title']} \\hfill {person['start']} to {person['end']}   \nProject: {person['project']}   \nNext position: {person['next_role']}  \n"
    markdown_output += foo
display(Markdown(markdown_output))
```

# Leadership Training

\hrule


```{python} 

# Read YAML file
with open("data/leadership-training.yaml", "r") as file:
    data = yaml.safe_load(file)
```





```{python}
# maybe add more fields to output??? ie, in call to Markdown?
# need to decide which fields matter when assembling my yaml file!
markdown_output = ""
for event in data['events']:
    foo = ""
    if event.get("date") is not None:
        date_str = event.get("date")
        date_obj = datetime.datetime.strptime(date_str, "%Y-%m")
        formatted_date = date_obj.strftime("%B %Y")
        event['term'] = formatted_date
            # handle end_date
    end_date_str =  event.get("end_date")
    if end_date_str is not None:
        end_date_obj = datetime.datetime.strptime(end_date_str, "%Y-%m")
        end_date_formatted = end_date_obj.strftime("%B %Y")
        formatted_date = f"{formatted_date} to {end_date_formatted}"
        event['term'] = formatted_date
    if event.get("url") is not None:
        url = event.get("url")
        #foo = f"\\footnotesize [{event['role']}, {event['event']}]({url}) \hfill {event['term']}  \n"
        foo = text_size_text + f"[{event['role']}, {event['event']}]({url}) \\hfill {event['term']}  \n"
    else:
   #     foo = f"\\footnotesize {event['role']}, {event['event']} \hfill {event['term']}  \n"
        foo = text_size_text + f"{event['role']}, {event['event']} \\hfill {event['term']}  \n"
    markdown_output += foo
display(Markdown(markdown_output))
```



# Awards & Honors

\hrule

```{python}
# Read YAML file
with open("data/awards.yaml", "r") as file:
    data = yaml.safe_load(file)
sorted_awards = sorted(data.get("awards", []), key=lambda x: x.get("year", 0), reverse=True)
markdown_output = ""
for award in sorted_awards:
    year = award.get("year")
    end_year = award.get("end_year")
    if end_year is not None:
        year = f"{year} to {end_year}"
    #markdown_output += f"\\footnotesize {award['title']}, {award['institution']} \hfill {year}  \n"
    markdown_output += text_size_text + f"{award['title']}, {award['institution']} \\hfill {year}  \n"
display(Markdown(markdown_output))
```



# Presentations

\hrule

```{python}
# Read YAML file
with open("data/presentations.yaml", "r") as file:
    data = yaml.safe_load(file)

sorted_presentations = sorted(data.get("presentations", []), key=lambda x: x.get("date"), reverse=True)

markdown_output_talks = ""
markdown_output_posters = ""

for presentation in sorted_presentations:
    foo = ""
    date_str = presentation.get("date")
    date_obj = datetime.datetime.strptime(date_str, "%Y-%m-%d")
    date_formatted = date_obj.strftime("%B %d, %Y")
    url = presentation.get("url")
    if url is not None:
#        foo = f"\\footnotesize [{presentation['title']}]({url}) \hfill {date_formatted}  \n{presentation['venue']} \hfill {presentation['location']}  \n"
        foo = text_size_text + f"[{presentation['title']}]({url}) \\hfill {date_formatted}  \n{presentation['venue']} \\hfill {presentation['location']}  \n"
    else:
        #foo = f"\\footnotesize {presentation['title']} \hfill {date_formatted}  \n{presentation['venue']} \hfill {presentation['location']}  \n"
        foo = text_size_text + f"{presentation['title']} \\hfill {date_formatted}  \n{presentation['venue']} \\hfill {presentation['location']}  \n"
    if presentation.get("presentation_type") == "talk":
        markdown_output_talks += foo
    elif presentation.get("presentation_type") == "poster":
        markdown_output_posters += foo
```      
      


## Slide Presentations

```{python}
display(Markdown(markdown_output_talks))
```



## Poster Presentations

```{python}
display(Markdown(markdown_output_posters))
```



# Service


\hrule


```{python}
# Read YAML file
with open("data/service.yaml", "r") as file:
    data = yaml.safe_load(file)
sorted_service = sorted(data.get("service", []), key=lambda x: max(x.get("date")), reverse=True)

markdown_output_university = ""
markdown_output_community = ""
markdown_output_professional = ""


for service in sorted_service:
    foo = ""
    # Accessing and formatting the dates as "Month Year"
    dates = service.get("date", [])
    formatted_dates = []
    for date_str in dates:
        date_obj = datetime.datetime.strptime(date_str, "%Y-%m")
        formatted_date = date_obj.strftime("%B %Y")
        # handle end_date
        end_date_str =  service.get("end_date")
        if end_date_str is not None:
            end_date_obj = datetime.datetime.strptime(end_date_str, "%Y-%m")
            end_date_formatted = end_date_obj.strftime("%B %Y")
            formatted_date = f"{formatted_date} to {end_date_formatted}"
        # handle current values
        if service.get("current") == 'true':
            formatted_date = f"{formatted_date} to present"
        formatted_dates.append(formatted_date)

    fd = ", ".join(formatted_dates)
    
    # handle those entries with multiple orgs
    organizations = service.get("organization", [])
    org_output = ", ".join(organizations)
    # handle those entries with url values
    url = service.get("url")
    if url is not None:
        #foo = f"\\footnotesize [{service['title']}]({url}), {org_output} \hfill {fd}  \n"
        foo = text_size_text + f"[{service['title']}]({url}), {org_output} \\hfill {fd}  \n"
    else:
        #foo = f"\\footnotesize {service['title']}, {org_output} \hfill {fd}  \n"
        foo = text_size_text + f"{service['title']}, {org_output} \\hfill {fd}  \n"
    if service.get("service_type") == "university":
        markdown_output_university += foo
    elif service.get("service_type") == "community":
        markdown_output_community += foo
    elif service.get("service_type") == "professional":
        markdown_output_professional += foo
```      
      



## University Service

```{python}
display(Markdown(markdown_output_university))
```



## Community Service

```{python}
display(Markdown(markdown_output_community))
```



## Professional Service

```{python}
display(Markdown(markdown_output_professional))
```


