---
title: "CV"
filters:
  - bold-my-name.lua
format:
    quarto-cv-pdf: 
      keep-tex: true
author: Frederick Boehm
date: last-modified
phone: 715-252-3929
address: "University of Michigan · 419 Waymarket DR · Ann Arbor, MI 48103 · USA"
email: frederick.boehm@gmail.com
fontsize: 11pt
github: fboehm # github account
orcid: 0000-0002-1644-5931 # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
web: fboehm.us
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: parsing-bib-files/boehm-article.bib
  collection: parsing-bib-files/boehm-incollection.bib
  software: parsing-bib-files/boehm-software.bib
  submitted: parsing-bib-files/boehm-unpublished.bib
  book: parsing-bib-files/boehm-book.bib
  misc: parsing-bib-files/boehm-misc.bib
  proceedings: parsing-bib-files/boehm-inproceedings.bib
validate-yaml: false
csl: chicago-fullnote-bibliography-boehm.csl
engine: knitr
---






# Education



:::: {.columns}

::: {.column width="70%"}

### University of Michigan
Postdoctoral Research Fellow, Department of Internal Medicine (NIH T32 training grant)  
Postdoctoral Research Fellow, Department of Biostatistics  

### University of Massachusetts Medical School
Postdoctoral Research Fellow, Department of Microbiology & Physiological Systems  

### University of Wisconsin-Madison
Postdoctoral Research Fellow, Department of Biostatistics and Medical Informatics  
Ph.D., Department of Statistics  
Postdoctoral Research Fellow, Molecular and Environmental Toxicology Center  
Assistant Researcher, Value-Added Research Center   


### University of Washington
Postdoctoral Research Fellow, Department of Biostatistics  

### University of Wisconsin-Madison
M.D., School of Medicine and Public Health  
M.S., Department of Population Health Sciences  
B.S., with Honors in Chemistry, Mathematics, and Biochemistry, College of Letters and Science  
:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="20%"}
Ann Arbor, Michigan, USA    
2023 to present    
2021 to 2023    

Worcester, Massachusetts, USA    
2019 to 2021  

Madison, Wisconsin, USA    
2019  
2011 to 2019  
2012 to 2014    
2011  


Seattle, Washington, USA  
2007 to 2009  

Madison, Wisconsin, USA  
2003 to 2007  
2003 to 2007  
1996 to 2001  

:::

::::
