---
name: Frederick 
surname: Boehm
position: "Postdoctoral Researcher"
address: "Department of Biostatistics, University of Michigan"
phone: +1 715 252 3929
www: fboehm.us
email: "frederick.boehm@gmail.com"
github: fboehm
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Bachelor of Science (Chemistry)", "2001", "University of Wisconsin-Madison", "Madison, Wisconsin, USA",
  "Master of Science (Population health sciences)", "2007", "University of Wisconsin-Madison", "Madison, Wisconsin, USA",
  "Doctor of Medicine", "2007", "University of Wisconsin-Madison", "Madison, Wisconsin, USA", 
  "Doctor of Philosophy (Statistics)", "2019", "University of Wisconsin-Madison", "Madison, Wisconsin, USA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Selected Awards & Honors



```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1996, "Wisconsin Academic Excellence Scholarship", "",
  2001, "University Bookstore award for outstanding undergraduate thesis", "",
  2001, "National Science Foundation Graduate Research Fellowship", "",
  2013, "New Arts Venture Challenge Award for collaborative research to complete the Victorian Eyes art exhibition", "",
  2013, "Research ethics fellowship to participate in the Integrating research ethics and scholarship program", "",
  2018, "Best poster award at the annual International Mammalian Genome Conference", ""
) %>% 
  brief_entries(
    Type,
    Year, 
    Desc
  )
```

# Selected Publications

```{r}
library(dplyr)

bibliography_entries("packages.bib") %>%
  arrange(desc(issued)) %>%
  dplyr::filter(unlist(issued) > 2014)
```

